//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAlumno")]
public interface IAlumno
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/nuevoAlumno", ReplyAction="http://tempuri.org/IAlumno/nuevoAlumnoResponse")]
    bool nuevoAlumno(string instalacion, string dni, string nombre, int edad);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/getAlumno", ReplyAction="http://tempuri.org/IAlumno/getAlumnoResponse")]
    string getAlumno(string instalacion, string dni);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/getAllAlumnos", ReplyAction="http://tempuri.org/IAlumno/getAllAlumnosResponse")]
    string getAllAlumnos();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAlumnoChannel : IAlumno, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AlumnoClient : System.ServiceModel.ClientBase<IAlumno>, IAlumno
{
    
    public AlumnoClient()
    {
    }
    
    public AlumnoClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AlumnoClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AlumnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool nuevoAlumno(string instalacion, string dni, string nombre, int edad)
    {
        return base.Channel.nuevoAlumno(instalacion, dni, nombre, edad);
    }
    
    public string getAlumno(string instalacion, string dni)
    {
        return base.Channel.getAlumno(instalacion, dni);
    }
    
    public string getAllAlumnos()
    {
        return base.Channel.getAllAlumnos();
    }
}
