//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAlumno.ReferenciaServicioAlumnoWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaServicioAlumnoWCF.IAlumno")]
    public interface IAlumno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/nuevoAlumno", ReplyAction="http://tempuri.org/IAlumno/nuevoAlumnoResponse")]
        bool nuevoAlumno(string instalacion, string dni, string nombre, int edad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/getAlumno", ReplyAction="http://tempuri.org/IAlumno/getAlumnoResponse")]
        string getAlumno(string instalacion, string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/getAllAlumnos", ReplyAction="http://tempuri.org/IAlumno/getAllAlumnosResponse")]
        string getAllAlumnos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/setAlumno", ReplyAction="http://tempuri.org/IAlumno/setAlumnoResponse")]
        bool setAlumno(string instalacion, string dni, string nombre, int edad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumno/deleteAlumno", ReplyAction="http://tempuri.org/IAlumno/deleteAlumnoResponse")]
        bool deleteAlumno(string instalacion, string dni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlumnoChannel : ClienteAlumno.ReferenciaServicioAlumnoWCF.IAlumno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlumnoClient : System.ServiceModel.ClientBase<ClienteAlumno.ReferenciaServicioAlumnoWCF.IAlumno>, ClienteAlumno.ReferenciaServicioAlumnoWCF.IAlumno {
        
        public AlumnoClient() {
        }
        
        public AlumnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlumnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool nuevoAlumno(string instalacion, string dni, string nombre, int edad) {
            return base.Channel.nuevoAlumno(instalacion, dni, nombre, edad);
        }
        
        public string getAlumno(string instalacion, string dni) {
            return base.Channel.getAlumno(instalacion, dni);
        }
        
        public string getAllAlumnos() {
            return base.Channel.getAllAlumnos();
        }
        
        public bool setAlumno(string instalacion, string dni, string nombre, int edad) {
            return base.Channel.setAlumno(instalacion, dni, nombre, edad);
        }
        
        public bool deleteAlumno(string instalacion, string dni) {
            return base.Channel.deleteAlumno(instalacion, dni);
        }
    }
}
